name: desafio_flutter
description: desafio_flutter.
version: 1.0.0+1

publish_to: none

environment:
  sdk: ^2.18.6

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.11.0
  dio: ^4.0.6
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

flutter_icons:
  image_path: assets/icon.png
  android: false
  ios: false
  web:
    generate: true
  windows:
    generate: false
  macos:
    generate: false
